- check_on: branch
  regex: ^feature/
  count: 1
  approvers:
    - user:patricklubach
    - user:racoon63
- regex: "^build(deps|deps-dev):*"
  approvers:
    - user:patricklubach
- default: true
  approvers:
    - user:patricklubach
