name: "approver"
description: "GitHub action that checks if approval rule matches"
inputs:
  approvers_file:
    description: "Relative path to the approver file."
    required: false
    default: ".approvers.yaml"
  token:
    description: A GitHub access token
    required: true
  pr_number:
    description: The number of the pull request to apply defined rules
    required: true
  set_reviewers:
    description: Decides whether the action sets the reviewers for the pull request. If set to true the reviewers are set and the action exits.
    required: false
    default: ""
runs:
  using: "node20"
  main: "src/index.js"
